### ISSUE TITLE
I want to reproduce your result. Can you provide the candidates of parallel-TE 

### ISSUE THREAD

**Issue by kiriyamashinnji** [jiangshdd/LearningToSelect#1]

**Comment by jiangshdd** [comment]
Hi,

Thanks for your interest in our work!

For the UFET task, here are the pretrained statement model and type vectors you can use directly to get the candidates.

- statement model: https://drive.google.com/file/d/1mnjTwMMuSlSHS-T74PMjGPQEaDPHA4l2/view?usp=share_link
- type vectors: https://drive.google.com/file/d/1mCCsObC-9orei6Y3ndie4uPLr0Wn97kJ/view?usp=sharing

For the intent detection task, you can use the sentence-bert checkpoint to get the candidates, which is written in the code:

- SentenceTransformer('multi-qa-mpnet-base-dot-v1')
